### PR TITLE
add CheckLicense class so we can verify the license when needed.

### PR DESCRIPTION
**Pull request by mwpeng**

### CODE REVIEW

**Comment by mwpeng** [comment]
line 105:
'getConfirmationStamp(java.lang.String)' is available only since 182.3911.6 but the module is targeted for 162.0+. It may lead to compatibility problems with IDEs prior to 182.3911.6.

@MrCoder we might need to update this

**Comment by MrCoder** [comment]
Let's update the target version (since-build). It does not make sense we say we support an earlier version that we do not really support.

**Comment by mwpeng** [comment]
> Let's update the target version (since-build). It does not make sense we say we support an earlier version that we do not really support.

fixed. @MrCoder

**Comment by MrCoder** [comment]
Merged to rel/20191. Closing this one.

**Pull request closed without merging**
